### ISSUE TITLE
measurement field overlap on demo.limbforge.org

### ISSUE THREAD

**Issue by andreasbastian** [limbforge/LimbForge#112]
## Problem
The measurement fields on the xradial measurement diagram (L and R) overlap (specifically C1 and C2).
![screenshot 2017-04-23 19 45 01](https://cloud.githubusercontent.com/assets/5185511/25320607/76a1641a-285d-11e7-8a94-9d11c3a015c5.png)

## Solution
-measurement fields shouldn't overlap for xradial measurement diagram

**Comment by kaitlynhova** [comment]
closed by https://github.com/limbforge/Limbforge/commit/477e006acb2257b66b2e52429f4a9c50a50b805d
