### ISSUE TITLE
Replace pop-out date selection 

### ISSUE THREAD

**Issue by andreasbastian** [limbforge/LimbForge#120]
## Problem
Currently, the date selection UI (a pop out calendar) is cumbersome for selecting dates more than a month before the current date.  
![screenshot 2017-09-09 15 25 23](https://user-images.githubusercontent.com/5185511/30244480-51faee46-9573-11e7-9b61-e1a7d2a21daa.png)

## Solution
-replace pop-out calendar with manual date entry in the dd-mm-yyy format:
![screenshot 2017-09-09 15 26 10](https://user-images.githubusercontent.com/5185511/30244482-5a84c4f6-9573-11e7-934c-0bbee959124f.png)

**Comment by kaitlynhova** [comment]
closed by https://github.com/limbforge/Limbforge/commit/25ee07365ccba7e8c573eeaae36d1050ce898e14
