### ISSUE TITLE
Email User Limbforge files

### ISSUE THREAD

**Issue by kaitlynhova** [limbforge/LimbForge#27]
Once the form is completely filled out, add a second option next to "Download files" that is "Email me the files". 

This will require
1) ActionMailer setup
2) attaching .zip files to ^^email

**Comment by matthova** [comment]
+1 for this. Using the app on mobile or tablet is a tease unless the final assets are emailed.

**Comment by kaitlynhova** [comment]
closing and adding to [Backlog project](https://github.com/limbforge/Limbforge/projects/3)'s RAW column to be fully specced out
