### ISSUE TITLE
Make .zip file download work on Safari

### ISSUE THREAD

**Issue by kaitlynhova** [limbforge/LimbForge#5]
Safari has a weird quirk to it, and for some reason it throws this error in the console instead of working:
<img width="943" alt="screen shot 2016-08-14 at 10 40 06 pm" src="https://cloud.githubusercontent.com/assets/5474124/17656545/164b1092-6270-11e6-94a5-f7cec1660a3e.png">

**Comment by matthova** [comment]
Fixed
