### ISSUE TITLE
Highlighting body type

### ISSUE THREAD

**Issue by hobe12** [limbforge/LimbForge#51]
Remove box with outline.  Replace with highlighted body outline. Make the body selected blue (with no outline) while the other one remains gray.

**Comment by kaitlynhova** [comment]
This now lives on the branch [new-fe](https://github.com/e-nable/Limbforge/tree/new-fe), and can be seen on [staging1](https://limbforge-staging1.herokuapp.com/limbforge).

**Comment by hobe12** [comment]
hova, can you please scale the female outline to match the size of the male one?  thx
