### ISSUE TITLE
Track patient data

### ISSUE THREAD

**Issue by luzlab** [limbforge/LimbForge#53]
We want to save the patient data. What else do we want to do with it?

**Comment by hobe12** [comment]
We want to capture it on a spreadsheet along with the other data we can pull from the tool.  Any inputs should be tracked (age, date, city, amputation cause, amputation level, gender, measurements, left/right, device selected, terminal device, etc...)

**Comment by kaitlynhova** [comment]
Closing and adding to [Backlog project](https://github.com/limbforge/Limbforge/projects/3)'s RAW column to be fully specced out
