### ISSUE TITLE
Add drop down for user of LF

### ISSUE THREAD

**Issue by hobe12** [limbforge/LimbForge#54]
Please add drop down menu for the person building the prosthetic:

Who is building this device?
-Prosthetist
-Patient
-3D Printing Enthusiast
-Designer
-Medical worker
-Aid worker
-Other (add text box to specify)

**Comment by kaitlynhova** [comment]
We are suspending this feature for now, but will come back to it. This is something that we can track on the user profiles potentially in the future.
