### ISSUE TITLE
Devices to have in LimbForge by Friday 1/27

### ISSUE THREAD

**Issue by andreasbastian** [limbforge/LimbForge#57]
1. ECF passive xradial (aka Ebe Arm)
2. ECF active xradial (aka Active Ebe Arm)
3. 3DLifePrints 3DLifeArm (active xradial)
4. ECF passive xhumeral

I will compile associated metadata and display models over the next day or two and email them out.

**Comment by kaitlynhova** [comment]
@hobe12 Can you slack me the icons for each of these?

**Comment by hobe12** [comment]
Buttons attached
[Device Buttons.zip](https://github.com/e-nable/Limbforge/files/730689/Device.Buttons.zip)

**Comment by kaitlynhova** [comment]
@hobe12 @andreasbastian will we have icons of the devices?

**Comment by kaitlynhova** [comment]
@hobe12 can you send me the svg for 3D Life arm? It doesn't render for me in the .zip for some reason

**Comment by kaitlynhova** [comment]
The meta data for the devices are all on http://limbforge-demo.herokuapp.com/limbforge

* I still need the endpoint and all of the lookup tables to grab the data from to display & download. How are those @andreasbastian & @luzlab ?

* @hobe12 do you have any ideas for the component button area? The buttons in the .zip you uploaded are too wide for the sidebar. It's about 350px wide.

If it's too short of notice to have that ready, you could maybe just display the run through with the ebe arm, and quickly show that there are components rendering for transhumeral as well?

**Comment by kaitlynhova** [comment]
Closing and adding to [Backlog project](https://github.com/limbforge/Limbforge/projects/3)'s RAW column to be fully specced out
