### ISSUE TITLE
icons for components

### ISSUE THREAD

**Issue by kaitlynhova** [limbforge/LimbForge#63]
<img width="712" alt="screen shot 2017-01-25 at 8 29 56 pm" src="https://cloud.githubusercontent.com/assets/5474124/22320021/25fae1ea-e33d-11e6-82a5-9a4ad41104db.png">

**Comment by hobe12** [comment]
Those are the buttons I posted in GH earlier.

**Comment by kaitlynhova** [comment]
It sounds like we are only using icons of the companies right now, not the actual devices.
