### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by hobe12** [limbforge/LimbForge#66]
Issues broken down by area and assigned to Sam - S, Kaitlyn - K, Matt - M
Cause of amputation
- [ ] K - Make “Please Select” be grey text. everything else black text
- [ ] K - Verify font for “First” and “Last” is consistent with the rest of the app

Select Gender
- [ ] K - Get rid of excess padding
- [ ] K - Verify no inconsistent fonts

Amputation
- [x] M - Reword orientation to be…. Side
- [ ] K - Align Orientation with Amputation
- [x] M - Remove, selected level: and unbold the result
- [ ] K- decrease typeface of "transhumeral, etc..."

	
ThreeJS
- [x] M - zoom out on cad so you can see the entire device
Note: Need to determine a preferred value for camera.position and camera.rotation from Andreas' device

Prosthesis
- [ ] S - Update device buttons

Measurements
- [ ] K - Modal should not require scrolling
- [x] M - Terminal devices is broken
- [x] M - Back from measurements to prosthesis is broken

Footer
- [ ] K - Make black bar and feedback the same height / style as the continue button/text boxes

General feel
- [ ] K - Make unavailable areas grey
- [ ] K - Continue buttons. make same height and width as select boxes
- [ ] K - gap to continue button needs to be identical on each
- [ ] K - SORRY, i really want this one!  give equal margin on left and right? - Debatable but not MVP
- [x] M - Add collapsing functionality to section arrows
- [ ] K - Add cursor pointer where necessary
- [ ] K - Get rid of spingbox effect

**Comment by kaitlynhova** [comment]
Not sure how much of this I can get to today, but i'll try and make it happen! Can you expand on these in detail?

**Comment by matthova** [comment]
@kaitlynhova I just expanded Sam's issues and added checkboxes.

**Comment by kaitlynhova** [comment]
closing to consolidate --- @hobe12  can you add these to the [Backlog project](https://github.com/limbforge/Limbforge/projects/3)'s RAW column to be fully specced out? I'm not sure where to start on this one
