### ISSUE TITLE
Amputation levels

### ISSUE THREAD

**Issue by hobe12** [limbforge/LimbForge#69]
Amputation Level

- [ ] blue boxes still cover text
- [ ] K- make all levels the same shade of blue with each section divided simply by a white line
- [ ] K- reposition section lines (work w sam if you are unsure of correct positions)
- [ ] K- remove circle button and replace with the blue box changing opacity indicating it is selected

**Comment by kaitlynhova** [comment]
Closing -- @hobe12  can you add these to the  [Backlog project](https://github.com/limbforge/Limbforge/projects/3)'s RAW column to be fully specced out? We need more info
