### ISSUE TITLE
Sam's misc. issues for K

### ISSUE THREAD

**Issue by hobe12** [limbforge/LimbForge#71]
- [ ] Please use Din Alt Bold for titles and Avenir Next for content text
- [x] Get rid of male/female text under images
- [x] decrease text size of selected amputation level
- [x] change device buttons to only be the logo and title- all other info in drop down menu
- [x] everything should be aligned with the text of the section tab (not the drop down arrow)
- [ ] adjust cad model to fit at 45 degree ang on screen
- [x] place measurement icons next to text input boxes (not above)

**Comment by kaitlynhova** [comment]
@hobe12 I think we should wait on the 45 degree angle on the screen because it's difficult for smaller screens to get the whole thing in the photo, and can you expand on the text alignment?

**Comment by kaitlynhova** [comment]
moving the fonts check box to it's own issue: https://github.com/e-nable/Limbforge/issues/77
