### ISSUE TITLE
Amputation level issues

### ISSUE THREAD

**Issue by hobe12** [limbforge/LimbForge#73]
## Problem
I have now tried on 2 computers, both using Chrome.  In both cases, the measurement boxes are not in the right places and cover text beyond the image of the body

**OS:**
![image](https://cloud.githubusercontent.com/assets/5396475/23573916/71ac5b6a-002e-11e7-901b-a2cd4cac7411.png)

**Chrome** : Version 55.0.2883.95 (64-bit)
**Screen shots**:
![levels](https://cloud.githubusercontent.com/assets/5396475/23573854/fdb561b6-002d-11e7-9c57-336200d2509f.jpeg)

![image](https://cloud.githubusercontent.com/assets/5396475/23573930/a946f170-002e-11e7-974e-7f05816d883a.png)

Notice how the blue bars do not line up with the amputation levels correctly.  At the top, the blue bar covers the text.

## Solution
- [ ] Align blue bars for male diagram
- [ ] Align blue bars for female diagram

**Comment by kaitlynhova** [comment]
@hobe12 is this still an issue?

**Comment by hobe12** [comment]
Yes- same on every comp

**Comment by hobe12** [comment]
Chrome: Version 55.0.2883.95 (64-bit)

Screen shot:
![levels](https://cloud.githubusercontent.com/assets/5396475/23573854/fdb561b6-002d-11e7-9c57-336200d2509f.jpeg)

Notice how the blue bars do not line up with the amputation levels correctly.  At the top, the blue bar covers the text.

**Comment by hobe12** [comment]
![image](https://cloud.githubusercontent.com/assets/5396475/23573916/71ac5b6a-002e-11e7-901b-a2cd4cac7411.png)

**Comment by hobe12** [comment]
![image](https://cloud.githubusercontent.com/assets/5396475/23573930/a946f170-002e-11e7-974e-7f05816d883a.png)

**Comment by kaitlynhova** [comment]
@hobe12 I still can't recreate this bug -- I've tried most everything. Can we revisit a redesign for this area?

**Comment by kaitlynhova** [comment]
closed by https://github.com/limbforge/Limbforge/pull/103
