### ISSUE TITLE
Parameters out of order

### ISSUE THREAD

**Issue by luzlab** [limbforge/LimbForge#78]
![screen shot 2017-02-09 at 4 20 50 pm](https://cloud.githubusercontent.com/assets/9924835/22808957/dd1b85a8-eee3-11e6-99a7-e0d71bbacd72.png)
 
Put the parameters in ascending numerical order

**Comment by andreasbastian** [comment]
De-prioritizing in favor of devoting time to getting measurements embedded in the diagram.

**Comment by kaitlynhova** [comment]
closing and adding to cards on [Backlog project](https://github.com/limbforge/Limbforge/projects/3)
