### ISSUE TITLE
Parameter ranges

### ISSUE THREAD

**Issue by luzlab** [limbforge/LimbForge#79]
Check with Peter on what the correct parameters ranges for the different measurements.

**Comment by andreasbastian** [comment]
Here are measurements from "The Measure of Man and Woman", a book that covers 99 and 1 percentile measurements of men and women with some discussion of geographic variations.  

The simplest approach will be to just make all of our models robust over 1% female to 99% male, a large, but comprehensive range.  In the future, if necessary, we can make the measurement ranges driven by gender selection and move to 1-99 percentile male/female.  Measurements below are from joint centers, not necessarily familiar anatomical land marks, but will be a good place to start.

99% male upper arm:  312mm (round to 31.5cm)
99% male forearm:  274mm (round to 27.5 cm)
1% female upper arm:  234mm (round to 23.0cm)
1% female forearm:  211mm (round to 21.0cm)

Circumferences aren't specified in MoMaW, so we may have to do a bit of digging n prosthetics catalogs or make extrapolations on a small set of measurements collected from friends/coworkers.

![img_6755](https://cloud.githubusercontent.com/assets/5185511/22864544/56b66614-f108-11e6-9125-ef62d673cff2.JPG)
![img_6754](https://cloud.githubusercontent.com/assets/5185511/22864545/58a394f6-f108-11e6-9d62-0f8562fd4c5f.JPG)

**Comment by kaitlynhova** [comment]
closing and adding to cards on [Backlog project](https://github.com/limbforge/Limbforge/projects/3)
