### ISSUE TITLE
Change "side" to "orientation" in 

### ISSUE THREAD

**Issue by luzlab** [limbforge/LimbForge#80]
![screen shot 2017-02-09 at 4 30 38 pm](https://cloud.githubusercontent.com/assets/9924835/22809151/1cc43226-eee5-11e6-8495-f6de69871f42.png)

One of the parameters sent to fusion360.io was renamed from "orientation" to "side". Let's change the name back...

**Comment by kaitlynhova** [comment]
I updated the parameters but it looks like it's still not working -- is the Fusion360.io up, @luzlab ?

After I click download I get this:

<img width="1181" alt="screen shot 2017-03-03 at 3 47 20 pm" src="https://cloud.githubusercontent.com/assets/5474124/23573128/bbb7f53a-0028-11e7-9c63-8b8d9893f4a0.png">

**Comment by kaitlynhova** [comment]
@luzlab endpoint is working now! Thanks! :D
