### ISSUE TITLE
Remove "l2" measurement from Transhumeral diagram

### ISSUE THREAD

**Issue by luzlab** [limbforge/LimbForge#81]
![screen shot 2017-02-09 at 4 34 04 pm](https://cloud.githubusercontent.com/assets/9924835/22809222/96a5be20-eee5-11e6-8c91-9879694828eb.png)

See Andreas for proper numbering (proximal to medial)

**Comment by kaitlynhova** [comment]
closing and adding to cards on [Backlog project](https://github.com/limbforge/Limbforge/projects/3)
