### ISSUE TITLE
Parameterizing forearms for differing wrist sizes

### ISSUE THREAD

**Issue by kaitlynhova** [limbforge/LimbForge#84]
We need to understand the best way to manage the XRA arm CAD.  

- [ ]  Game Plan for New CAD file(s)
        - wrist (standard)
        - forearm (L/R | parametric)
        - Terminal Device (L/R sizes: S, M, L)

**Comment by andreasbastian** [comment]
using continuous control on TDs until discrete behavior can be encoded into the Fusion model for the TDs
